### ISSUE TITLE
Mac Installation Security Issues

### ISSUE THREAD

**Issue by un-focused** [btq-ag/keelung-compiler#26]
When installing the keelungc binary, MacOS stops it from being executed. It might be useful to walk users through this process explaining how to fix this.

<img width="270" alt="image" src="https://github.com/btq-ag/keelung-compiler/assets/68040163/b7ccbb48-cc71-488f-aa32-eb2fa09944a1">

**Comment by un-focused** [comment]
Then run the command you were running previously. It will give a warning.

<img width="256" alt="image" src="https://github.com/btq-ag/keelung-compiler/assets/68040163/081b0656-dead-4611-95e8-ba601ef4a733">

**Comment by un-focused** [comment]
Then press allow

**Comment by banacorn** [comment]
Hi, thank you for reporting this!

It's expected for the downloaded binaries of the compiler (or any other binaries on the internet) to trigger this kind of warning when you try to execute it for the first time. 

Question: does this warning still persist even if you have pressed the "Allow Anyway" button from your second screenshot?

**Comment by banacorn** [comment]
Because the compiler has been open sourced just recently, you can now also build the binary directly from the source.

Clone this repository, checkout to `v0.13.0` and execute `stack install` and you should have a working compiler binary on your PATH!

I'll close this issue after all these have been documented

**Comment by un-focused** [comment]
That is awesome! It does not happen afterwards and I agree that this is bound to happen because it's a binary from the internet. It's basically complaining that it's not verified by Apple. I ended up just getting the binary from the releases section in the GitHub.

Adding what you mentioned to the documentation would be super useful. I was looking for how I could build it from source!
