### ISSUE TITLE
Add REPL Quit Documentation

### ISSUE THREAD

**Issue by un-focused** [btq-ag/keelung-compiler#27]
I was trying to quit the REPL and found that to quit you have to use Ctrl + D which makes sense. It can be confusing as usually commands such as exit, quit are used as well.

Adding documentation for this matter would be useful.

**Comment by banacorn** [comment]
We're actually using GHCi as Keelung's REPL, [here's the manual of GHCi](https://downloads.haskell.org/ghc/latest/docs/users_guide/ghci.html).

Try `:help` and you should see commands like `:quit`!

**Comment by un-focused** [comment]
I think this should be mentioned in the documentation.

**Comment by un-focused** [comment]
The Python and Node REPL quit in different ways so it can be confusing. I think just mentioning this in the documentation would be awesome!
